package com.example.customlistview

import android.content.Intent
import android.os.Bundle
import android.widget.ListView
import android.widget.Toast
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat

class MainActivity : AppCompatActivity() {
    val profileName =
        arrayOf("Musfique Rahim", "Sakib Al Hasan", "Mahmudullah Riyad", "Masrafe Bin Mortaza")
    val profileDes = arrayOf<String>(
        "Right hand wickerkeeper",
        "No 1 al rounder",
        "Left hand opener batsman",
        "Al rounder finisher",
        "Fast medium bowler and captain"
    )
    val images = arrayOf<Int>(
        R.drawable.musfiquerahim,
        R.drawable.sakib,
        R.drawable.tamim,
        R.drawable.mahmudullah,
        R.drawable.marhrafe
    )
    val longDesc = arrayOf(
        "Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team ",
        "Sakib Rahim (Bengali: born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team ",
        "Tamim Rahim (Bengali:  born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team ",
        "Mahmudullah Rahim (Bengali:  born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team ",
        "Mashrafe Rahim (Bengali:  born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team Mushfiqur Rahim (Bengali: মুশফিকুর রহিম born 9 May 1987) is a Bangladeshi cricketer and the former captain of the Bangladesh national cricket team. He is a right-handed middle-order batsman and wicket-keeper in the national team "
        )

    lateinit var listView: ListView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_main)
        listView = findViewById(R.id.listView)

        val myListAdapter = MyListAdapter(this,profileName, profileDes, images)
        listView.adapter = myListAdapter

        listView.setOnItemClickListener{parent,view,position,id ->
            Toast.makeText(this,"Clicked At ${parent.getItemAtPosition(position)}", android.widget.Toast.LENGTH_SHORT).show()
            var intent = Intent (this, DetalsActivity::class.java)
            intent.putExtra("name",profileName[position])
            intent.putExtra("image",images[position])
            intent.putExtra("desc",longDesc[position])
            startActivity(intent)
        }
    }
}